// Generated by ts-to-zod
import { z } from "zod";
import { Priority } from "./../atoms/tasks";

export const confidenceSchema = z.union([
  z.literal("high"),
  z.literal("medium"),
  z.literal("low"),
]);

export const prioritySchema = z.nativeEnum(Priority);

export const taskSchema = z.object({
  id: z.string(),
  title: z.string(),
  team: z.object({
    id: z.string(),
    name: z.string(),
  }),
  assignee: z
    .object({
      id: z.string(),
      name: z.string(),
    })
    .nullable(),
  due_date: z.string().nullable(),
  priority: prioritySchema,
  description: z.string(),
  tags: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
    }),
  ),
  confidence: confidenceSchema,
  url: z.string().optional(),
});
